name: mbesgc
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - GDAL==3.8.3
  - numpy==1.26.4
  - pyproj==3.6.1
  - scipy
  - pip
  - pip:
    - pytest
    - click==8.1.3
    - affine==2.4.0
    - git+https://github.com/ausseabed/qajson.git

